Dev feature/#6
fuchicorp/terraform-google-gke pull request #7
Opened 2021-04-22 17:27 UTC by slimflex2

2021-04-22 17:30 UTC, slimflex2 commented
https://github.com/fuchicorp/terraform-google-gke

2021-04-23 23:07 UTC, fsadykov requested changes
Needs to work on !!

2021-04-23 23:07 UTC, fsadykov commented on variable.tf
> +  default     = "False"
This line needs to be fixed. I am not sure `"False"` is terraform boolean

2021-04-23 23:07 UTC, fsadykov commented on main.tf
> +    disk_size_gb     = "${var.disk_size_in_gb}"
Please fix the indentation

2021-04-23 23:08 UTC, ksalrin approved these changes

2021-04-23 23:08 UTC, seckinemrah approved these changes

2021-04-23 23:08 UTC, hyvz-devops approved these changes

2021-04-23 23:13 UTC, fsadykov requested changes

2021-04-23 23:13 UTC, fsadykov commented on deployment/example/module.tf
> +    cluster_name = "fuchicor-cluster"
Please fix to `fuchicorp-cluster`

2021-04-23 23:13 UTC, fsadykov commented on variable.tf
> +variable "auto_upgrade" {
You have two variables added but not see them in README.md file. Make sure you include the variables in the table

2021-04-30 23:32 UTC, fsadykov approved these changes
Looks good to me

2021-04-30 23:32 UTC, merged

2021-04-30 23:32 UTC, balloray approved these changes